name: Build Oolite on Fedora and Arch
on:
  push:
  pull_request:

jobs:
  fedora:
    runs-on: ubuntu-latest
    container: fedora:36
    steps:
      - uses: actions/checkout@v6
      - name: Checkout dependencies
        run: |
          dnf -y update
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages and build Oolite
        run: |
          DevEnvironments/Linux/install.sh release

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v6
      - name: Checkout dependencies
        run: |
          pacman -Sy --noconfirm
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages and build Oolite
        run: |
          DevEnvironments/Linux/install.sh release
