name: Build Oolite on Fedora and Arch
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Fedora 36
            container: fedora:36
          - name: Arch latest
            container: archlinux:latest

    name: ${{ matrix.name }}
    container:
      image: ${{ matrix.container }}
      options: --privileged  # sometimes needed for Docker-in-Docker or low-level ops
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh

      - name: Install packages and build Oolite
        run: |
          DevEnvironments/Linux/install.sh release
