name: Build Oolite on Fedora and Arch
on:
  push:
  pull_request:

jobs:
  fedora:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - name: Update Fedora
        run: |
          dnf -y update
          dnf -y install git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages and build Oolite
        run: |
          DevEnvironments/Linux/install.sh release

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Update Arch
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm --needed git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages and build Oolite
        run: |
          DevEnvironments/Linux/install.sh release
