name: Build Oolite package on various platforms
on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          sudo DevEnvironments/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          DevEnvironments/Linux/build_oolite.sh pkg-appimage

  flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: |
          sudo apt-get update
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Calculate version number and set OOLITE_VERSION
        id: version
        run: |
          set -x
          # Build version string,
          # taking into account that we may have just two digits
          VERSION=$(cat src/Cocoa/oolite-version.xcconfig | cut -d '=' -f 2)
          VER_MAJ=$(echo ${VERSION} | cut -d. -f1)
          VER_MIN=$(echo ${VERSION} | cut -d. -f2)
          VER_REV=$(echo ${VERSION} | cut -d. -f3)
          if [ "" == "${VER_REV}" ]
          then
            VER_REV="0"
          fi
          VER_DATE=$(date +%y%m%d)
          VER_GITREV=$(git rev-list --count HEAD)
          VER_GITHASH=$(git rev-parse --short=7 HEAD)
          VER="${VER_MAJ}.${VER_MIN}.${VER_REV}.${VER_GITREV}-${VER_DATE}-${VER_GITHASH}"
          echo "OOLITE_VERSION=${VER}" >> "$GITHUB_OUTPUT"
          echo "OOLITE_VERSION=${VER}" >> Doc/OOLITE_VERSION.txt
      - name: Set flatpak version
        run: |
          release_tag="<release version=\"$(cat Doc/OOLITE_VERSION.txt)\" date=\"$(date -I)\"></release>"
          sed -i "/<releases>/a $release_tag" installers/flatpak/org.ooliteproject.Oolite.metainfo.xml
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.ooliteproject.Oolite.flatpak
          manifest-path: installers/flatpak/org.ooliteproject.Oolite.yaml

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: >-
        --cap-add SYS_ADMIN
        --device /dev/fuse
        --security-opt apparmor:unconfined
    steps:
      - name: Update Fedora
        run: |
          dnf -y update
          dnf -y install git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          DevEnvironments/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          DevEnvironments/Linux/build_oolite.sh pkg-appimage

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: >-
        --cap-add SYS_ADMIN
        --device /dev/fuse
        --security-opt apparmor:unconfined
    steps:
      - name: Update Arch
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm --needed git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          DevEnvironments/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          DevEnvironments/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          DevEnvironments/Linux/build_oolite.sh pkg-appimage
