name: Build Oolite package on various platforms
on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          ShellScripts/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          sudo ShellScripts/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          ShellScripts/common/build_oolite.sh pkg-appimage

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: >-
        --cap-add SYS_ADMIN
        --device /dev/fuse
        --security-opt apparmor:unconfined
    steps:
      - name: Update Fedora
        run: |
          dnf -y update
          dnf -y install git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          ShellScripts/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          ShellScripts/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          ShellScripts/common/build_oolite.sh pkg-appimage

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: >-
        --cap-add SYS_ADMIN
        --device /dev/fuse
        --security-opt apparmor:unconfined
    steps:
      - name: Update Arch
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm --needed git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout dependencies
        run: |
          ShellScripts/Linux/checkout_deps.sh
      - name: Install packages
        run: |
          ShellScripts/Linux/install_deps_root.sh
      - name: Build Oolite
        run: |
          ShellScripts/common/build_oolite.sh pkg-appimage
